### ISSUE TITLE
Specify gene ID type?

### ISSUE THREAD

**Issue by Ni-Ar** [sgrote/GOfuncR#10]
Hi, 

I saw in the examples that the genes are identified by their names. Is it possible to specify them by their ENSEMBL gene id?

Thanks,
Nicco

**Comment by sgrote** [comment]
Hi Nicco,

no, the package assumes that you provide gene symbols.
Alternatively, you might provide your own annotations of Ensembl IDs to GO-terms  (and the ontology itself, if needed) as described [here](https://bioconductor.org/packages/release/bioc/vignettes/GOfuncR/inst/doc/GOfuncR.html#enrichment-analyses-with-different-annotations-or-ontologies).

Cheers,
Steffi

**Comment by Ni-Ar** [comment]
Okay, thanks for clarifying this Steffi.
