### ISSUE TITLE
Using GOfuncR to do custom enrichment analysis of bacteria

### ISSUE THREAD

**Issue by minisciencegirl** [sgrote/GOfuncR#2]
I am interested in using GOfuncR to do enrichment analysis using custom GO annotations for bacteria. As there are not many bacteria with annotation dbi package, this is unfortunately the only way I can think of to do this.

So I followed the vignette section 3.2, where I build a custom_GO dataframe based on GO annotations that I downloaded, with the first column be `gene` and the second column be associated `go_id`. My input_hyper is set up with the first column as `gene_ids` of all genes identified from DE analysis and the second column as `is_candidate`.

After I ran this line: `res_hyper_anno = go_enrich(input_hyper, annotation = custom_GO)`, I get the following errors:

Checking arguments...
Write temporary files...
Find associated categories using custom annotations...
Remove annotated categories not present in GO-graph...
Error in get_anno_categories(database = anno_db, annotations = annotations,  : 
  No valid GO-annotations found for the input genes.

How should I go about troubleshooting this?

Thanks!

**Comment by sgrote** [comment]
Hi, the steps you took seem fine. Could you maybe provide a minimal example to replicate the issue?
So just some genes in `input_hyper` and their GO-annotations in `custom_GO`?

**Comment by minisciencegirl** [comment]
I am attaching two files of input_hyper and custom_GO. Here is my code to make `input_hyper` and `custom_GO`:

```
relvsWT.p.genes <- relvsWT.p$X
input_hyper <-  data.frame(relvsWT.p.genes, is_candidate=1) %>% 
  dplyr::rename("gene_ids"= "relvsWT.p.genes") 
write.table(input_hyper, "input_hyper.txt", quote = FALSE, sep = "\t", row.names = FALSE)

custom_GO <- GO %>% 
  dplyr::select(Locus.Tag, Accession)  %>% 
  dplyr::rename("gene" = "Locus.Tag") %>% 
  dplyr::rename("go_id" = "Accession")
write.table(custom_GO, "custom_GO.txt", quote = FALSE, sep = "\t", row.names = FALSE)
```

[custom_GO.txt](https://github.com/sgrote/GOfuncR/files/2469832/custom_GO.txt)
[input_hyper.txt](https://github.com/sgrote/GOfuncR/files/2469833/input_hyper.txt)

**Comment by sgrote** [comment]
Unfortunately I cannot reproduce the error. For me
```
input_hyper = read.table("input_hyper.txt", header=T, stringsAsFactors=F)
custom_GO = read.table("custom_GO.txt", header=T, stringsAsFactors=F)
res_hyper_anno = go_enrich(input_hyper, annotations = custom_GO)
```
works just fine.
Could you tell me your output of:
```
str(input_hyper)
str(custom_GO)
```
and
```
anno = get_anno_categories(input_hyper[,1], annotations=custom_GO)
str(anno)
```

**Comment by minisciencegirl** [comment]
Thank you for testing it out for me. I think the problem lies in that custom_GO is actually a tibble and not a data.frame. When I coerce it into a data.frame, then it works. Thanks again.
