### ISSUE TITLE
Results contain GO terms not in input custom annotations

### ISSUE THREAD

**Issue by travis-m-blimkie** [sgrote/GOfuncR#3]
Hello, I have been using GofuncR to perform GO term enrichment in bacteria, using a set of custom GO annotations downloaded from pseudomonas.com. When running the hypergeometric test, with a list of DE genes from RNASeq as my query, and using the downloaded GO terms for annotations, the resulting enrichment list contains terms that are not present in the custom GO annotations I provide. Just wondering how this could occur? Are such terms still valid? I have included the code and files in question. 

relvsWT.p.genes <- relvsWT.p$X
input_hyper <-  data.frame(relvsWT.p.genes, is_candidate=1, stringsAsFactors = FALSE) %>% 
  dplyr::rename("gene_ids"= "relvsWT.p.genes") 
write.csv(input_hyper, file = "input_hyper.csv", row.names = F, quote = F)

custom_GO <- GO %>% 
  dplyr::select(Locus.Tag, Accession) %>% 
  group_by(Locus.Tag) %>% 
  dplyr::rename("gene" = "Locus.Tag") %>% 
  dplyr::rename("go_id" = "Accession") %>% 
  as.data.frame()
write.csv(custom_GO, file = "custom_GO.csv", row.names = F, quote = F)

res_hyper_anno = go_enrich(input_hyper, annotation = custom_GO)
GO.relvsWT.p <- res_hyper_anno[[1]] %>% 
  filter(ontology == "biological_process") %>% 
  filter(raw_p_overrep < 0.05)
write.csv(GO.relvsWT.p, "GO_relvsWT_bp.csv", row.names = F, quote = F)

[custom_GO.txt](https://github.com/sgrote/GOfuncR/files/2516933/custom_GO.txt)
[GO_relvsWT_bp.txt](https://github.com/sgrote/GOfuncR/files/2516935/GO_relvsWT_bp.txt)
[input_hyper.txt](https://github.com/sgrote/GOfuncR/files/2516936/input_hyper.txt)

Example GO terms in the output, but not input annotations, include: GO:0046379 and GO:0033036. 

Thanks for your time,
--
Travis

**Comment by sgrote** [comment]
Hi Travis,
this is because the gene ontology is a graph, and if a gene is annotated to a specific node A, it automatically gets annotated to all the parent nodes of that node A in the enrichment analysis.

So in your example GO:0046379 is a parent node of GO:0045226, which is part of your annotation file.
You can find that out like this:
```
library(GOfuncR)
anno = read.csv("custom_GO.txt", header=T, stringsAsFactors=F)
input_go_ids = unique(anno[,2])
mysterious_go_id = "GO:0046379"
child_nodes = get_child_nodes(mysterious_go_id)
input_go_ids[input_go_ids %in% child_nodes$child_go_id]
```

Let me know if this is unclear.

Cheers,
Steffi

**Comment by travis-m-blimkie** [comment]
Great, thanks for the help!

Cheers, 
Travis
