### ISSUE TITLE
Problem with get_parent_nodes

### ISSUE THREAD

**Issue by ArthurPERE** [sgrote/GOfuncR#4]
Hello,

I have a problem with the get_parent_nodes or get_child_nodes, I don't realy know, this is my script :

```
> library(GOfuncR)
> library(data.table)
> library(purrr)

> GO_all = get_ids("biological_process") %>% pluck("go_id") %>% get_child_nodes() %>% setDT()

> GO_all[distance == 2, child_go_id]%>% unique() %>%  get_parent_nodes() %>% pluck("distance") %>% max
12

> GO_all[distance == 2, child_go_id] %>% unique %>% get_parent_nodes() %>% pluck("parent_go_id") -> parent
> GO_all[child_go_id %in% parent]
      parent_go_id child_go_id                                                      child_name distance
   1:   GO:0008150  GO:0008150                                              biological_process        0
   2:   GO:0008150  GO:0000003                                                    reproduction        1
   3:   GO:0008150  GO:0001906                                                    cell killing        1
   4:   GO:0008150  GO:0002376                                           immune system process        1
   5:   GO:0008150  GO:0006791                                              sulfur utilization        1
  ---                                                                                                  
1508:   GO:0008150  GO:0071901 negative regulation of protein serine/threonine kinase activity        8
1509:   GO:0008150  GO:0071902 positive regulation of protein serine/threonine kinase activity        8
1510:   GO:0008150  GO:1905508           protein localization to microtubule organizing center        8
1511:   GO:0008150  GO:0007204      positive regulation of cytosolic calcium ion concentration        9
1512:   GO:0008150  GO:0071988                       protein localization to spindle pole body        9
```

The first line is where I stand at the root of the tree and go down into the tree. Then I take the GOs that are at the distance of 2 from the root and I take those parents. So logically, the maximum distance we should find would be 2, but here it is 12.

When I take all GO_id at the distance of 2 from the root, and take all the parent, and confront all the GO_id to the already made table where we have all the GO from the root. But as we can see there is distances from the root that is superior to 2, which is ilogical.

Thank you,
Arthur

**Comment by sgrote** [comment]
Hi Arthur,
sorry for the late response.

Your observations are actually not ilogical, given the structure of the GO graph.
I agree that it might be counter-intuitive, but having a distance of 2 to the root node, doesn't mean you don't have another ancestor with a higher distance.
Checkout the ancestor graph of this example and it will become clearer:
https://www.ebi.ac.uk/QuickGO/term/GO:0000075

Best,
Steffi
