### ISSUE TITLE
I could not find the instruction on how to use plot_binom.R,plot_conti.R function

### ISSUE THREAD

**Issue by xinhuiwang** [sgrote/GOfuncR#6]
GoFuncR is a nice package and I would like to have more output figures, unfortunately, I could not find the instruction of the following function (what is the input?)
[plot_binom.R](https://github.com/sgrote/GOfuncR/blob/master/R/plot_binom.R)
[change pie-charts for plot_hyper and plot_binom to clock-like orienta…](https://github.com/sgrote/GOfuncR/commit/2e730a67d6d37e000775e336b95136267c18c992)
5 years ago
[plot_conti.R](https://github.com/sgrote/GOfuncR/blob/master/R/plot_conti.R)
[fix typos](https://github.com/sgrote/GOfuncR/commit/6867cd71364072cb0a8cbdd16c655d3b7d0fd6c3)
5 years ago
[plot_hyper.R](https://github.com/sgrote/GOfuncR/blob/master/R/plot_hyper.R)
[fix typos](https://github.com/sgrote/GOfuncR/commit/6867cd71364072cb0a8cbdd16c655d3b7d0fd6c3)
5 years ago
[plot_wilcox.R](https://github.com/sgrote/GOfuncR/blob/master/R/plot_wilcox.R)
[implement custom GO-graph and annotations in remaining functions](https://github.com/sgrote/GOfuncR/commit/900de3fb4aace79e542948f9837b1759d1f4c5d9)

**Comment by sgrote** [comment]
Hi, those are only internal helper functions.  
They get called in `plot_anno_scores` [here](https://github.com/sgrote/GOfuncR/blob/master/R/plot_anno_scores.R#L99-L107).
So using `plot_anno_scores` will already use these functions.
