### ISSUE TITLE
What term to use for REVIGO Analysis?

### ISSUE THREAD

**Issue by desmodus1984** [sgrote/GOfuncR#9]
Hi,
I am studying RNA expression in bumblebees, and I have RNA-seq data, which I processed with DESeq2.
I have different treatments and I am interested in annotating differentially expressed genes.
I prepped the datasets for go_enrich tests, and then I was told to further "refine the results" with a FWR correction.
I have about 12000+ loci, and since the enrich test using random sets, I set the random-set parameter to 50000, for consistency/reproducibility in the results.
I was then told to further summarise the results with REVIGO, but it required a value, and I am not sure which one should I use.
The refine output has different "p-values", raw_p_underrep, raw_p_overrep, refined_p_overrep. Since I am "refining" the results, I used the last one.
I wanted to inquire this with you, to make sure that it is proper or correct, or else, with the refine out, REVIGO go_summary is unnecessary.

Thanks;

**Comment by sgrote** [comment]
Hi,

I'm not familiar with REVIGO analyses, but I think their method to remove redunancy in lists of GO-terms is different from using the child-parent relationsships that we use in GOfuncR. IMHO I think there is nothing wrong with trying out REVIGO if you find the list of enriched GO-terms too long to interpret, even after the refinement implemented in GOfuncR.   

And yes, if you are interested in GO-terms where your candidate genes are overrepresented, `refined_p_overrep` should be your column.

Best,
Steffi
